---

- name: "configuration play." 
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  
  environment:
    VERSION: 1
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PORT: 5432 
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      shell: sleep 2
    - name: "echo env varibales"
      shell: | 
        echo $ANSIBLE_HOST_KEY_CHECKING
        echo $TYPEORM_USERNAME  
  roles:
    - configure-server