- name: "Create backend deployment folder"
  become: true 
  shell: | 
    mkdir -p /opt/app/backend

- name: "copy backend files"
  become: true 
  copy:
    src: ~/projects/udacity/dev-ops/projects/udacity-devops-cicd-project/backend/dist/
    dest: /opt/app/backend/

- name: "copy done"
  shell: echo "Done" 