- name: "copy backend files"
  become: true 
  copy:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/
    owner: ubuntu

- name: "Uncompress Backend"
  shell: |
    cd /home/ubuntu/backend
    tar -xvf /root/project/backend.tar.gz

# - name: "Run server"
#   shell: |
#     cd ~/backeend
#     npm install
#     npm run start